ENTER ignore
/ ignore

s ignore
S screenshot

> playlist-next; script-message osc-playlist 1
< playlist-prev; script-message osc-playlist 1
TAB script-message osc-playlist 3

a cycle audio

# r add sub-pos -1 
# t add sub-pos +1 
R ab-loop
T script-message-to seek_to toggle-seeker

- add volume -5
= add volume 5; set mute "no"; show_text "Volume: ${volume}%"
+ set volume 100; set mute "no"; show_text "Volume: ${volume}%"

h seek -10 exact
j seek 1 exact
k seek -1 exact
l seek 10 exact

{ ignore
} ignore
[ add speed -0.25
] add speed 0.25

Alt+L cycle-values loop-playlist yes no; show-text "${?=loop-playlist==inf:Loop playlist: inf}${?=loop-playlist==no:Loop playlist: no}"

Ctrl+- add audio-delay -0.100
Ctrl+= add audio-delay 0.100

9 add sub-scale -0.1
0 add sub-scale +0.1

WHEEL_DOWN add volume -5
WHEEL_UP add volume 5; set mute "no"; show_text "Volume: ${volume}%"
0x5 add volume -5
0x19 add volume 5; set mute "no"; show_text "Volume: ${volume}%"

LEFT seek -10 exact
DOWN add volume -5
UP add volume 5; set mute "no"; show_text "Volume: ${volume}%"
RIGHT seek 10 exact

Alt+BS set video-zoom 0; set video-pan-x 0; set video-pan-y 0; show-text "Pan and zoom reset"

Alt+- add video-zoom -0.1 
Alt+= add video-zoom  0.1

Alt+h add video-pan-x  0.1
Alt+j add video-pan-y -0.1
Alt+k add video-pan-y  0.1
Alt+l add video-pan-x -0.1

Ctrl+f vf toggle hflip; show-text ""

Ctrl+r cycle_values video-rotate "90" "180" "270" "0"; show_text ""
Ctrl+R cycle_values video-rotate "0" "270" "180" "90"; show_text ""

~ set gamma 0; set saturation 0; set contrast 0; set brightness 0; show-text "All color adjustments reset"
