# /etc/mpv/mpv.conf x11 from wayland
# hwdec=vaapi-copy
# gpu-context=x11egl

input-ipc-server=/tmp/mpvsocket
screenshot-directory=~/Screenshots

title="[${playlist-pos-1}/${playlist-count}] ${media-title}"

geometry=1280x720
keepaspect-window=no
no-window-dragging
ytdl-format=best+bestaudio

volume=100
volume-max=150

osd-duration=2500
osd-bar-align-y=0.8
osd-bar-h=2
osd-border-size=2
osd-font-size=24
osd-level=1
osd-on-seek=msg
script-opts=osc-boxalpha=80
