# https://alacritty.org/config-alacritty.html

[font]
bold = { style = 'Regular' }
italic = { style = 'Regular' }
bold_italic = { style = 'Regular' }
# normal = { family = 'JetBrainsMono' }
normal = { family = 'Menlo' }
size = 12

[cursor]
style = { blinking = 'Always', shape = 'Block' }
blink_timeout = 0
blink_interval = 750
thickness = 0.1

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
foreground = '0xffffff'
background = '0x000000'

[colors.normal]
black   = '0x000000'
red     = '0xcc0000'
green   = '0x00cc00'
yellow  = '0xcc7700'
blue    = '0x0000ff'
magenta = '0xcc00cc'
cyan    = '0x00cccc'
white   = '0xcccccc'

[colors.bright]
black   = '0x777777'
red     = '0xff7777'
green   = '0x77ff77'
yellow  = '0xffff77'
blue    = '0x7777ff'
magenta = '0xff77ff'
cyan    = '0x77ffff'
white   = '0xffffff'

[colors.footer_bar]
foreground = '0xcc7700'
background = '0x000000'

[colors.search.focused_match]
foreground = '0xffffff'
background = '0xcc7700'

[colors.search.matches]
foreground = '0x000000'
background = '0xffff77'

[window]
dimensions = { columns = 80, lines = 24 }

[keyboard]
bindings = [
 { key = 'F11', action = 'ToggleFullscreen' },
 { key = '0', mods = 'Control', action = 'None' },
 { key = '-', mods = 'Control', action = 'None' },
 { key = '=', mods = 'Control', action = 'None' },
 { key = ')', mods = 'Control|Shift', action = 'ResetFontSize' },
 { key = '_', mods = 'Control|Shift', action = 'DecreaseFontSize' },
 { key = '+', mods = 'Control|Shift', action = 'IncreaseFontSize' },
]

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = ''
hyperlinks = false
post_processing = false
persist = false
mouse.enabled = false
regex = ''
