export FZF_DEFAULT_OPTS=""

export FZF_DEFAULT_OPTS+=" --layout=reverse"
export FZF_DEFAULT_OPTS+=" --no-bold"
export FZF_DEFAULT_OPTS+=" --no-separator"
export FZF_DEFAULT_OPTS+=" --marker='+'"
export FZF_DEFAULT_OPTS+=" --pointer=' '"
export FZF_DEFAULT_OPTS+=" --prompt='  '"
export FZF_DEFAULT_OPTS+=" --scrollbar='█ '"
export FZF_DEFAULT_OPTS+=" --no-mouse"

export FZF_DEFAULT_OPTS+=" --preview-window=bottom,border-sharp"

export FZF_DEFAULT_OPTS+=" --color=fg:-1"
export FZF_DEFAULT_OPTS+=" --color=fg+:-1:reverse"
export FZF_DEFAULT_OPTS+=" --color=bg:-1"
export FZF_DEFAULT_OPTS+=" --color=bg+:-1"
export FZF_DEFAULT_OPTS+=" --color=hl:-1"
export FZF_DEFAULT_OPTS+=" --color=hl+:-1:reverse"
export FZF_DEFAULT_OPTS+=" --color=border:8"
export FZF_DEFAULT_OPTS+=" --color=info:8"
export FZF_DEFAULT_OPTS+=" --color=marker:11"
export FZF_DEFAULT_OPTS+=" --color=pointer:8"
export FZF_DEFAULT_OPTS+=" --color=preview-border:8"
export FZF_DEFAULT_OPTS+=" --color=prompt:8"
export FZF_DEFAULT_OPTS+=" --color=scrollbar:8"
export FZF_DEFAULT_OPTS+=" --color=separator:8"
export FZF_DEFAULT_OPTS+=" --color=spinner:8"

export FZF_DEFAULT_OPTS+=" --bind=esc:ignore"
export FZF_DEFAULT_OPTS+=" --bind=ctrl-g:ignore"
export FZF_DEFAULT_OPTS+=" --bind=ctrl-q:ignore"

export FZF_DEFAULT_OPTS+=" --bind=ctrl-j:accept"
export FZF_DEFAULT_OPTS+=" --bind=ctrl-k:kill-line"

export FZF_DEFAULT_OPTS+=" --bind=ctrl-d:half-page-down"
export FZF_DEFAULT_OPTS+=" --bind=ctrl-u:half-page-up"
export FZF_DEFAULT_OPTS+=" --bind=ctrl-f:page-down"
export FZF_DEFAULT_OPTS+=" --bind=ctrl-b:page-up"
export FZF_DEFAULT_OPTS+=" --bind=alt-g:first"
export FZF_DEFAULT_OPTS+=" --bind=alt-G:last"

export FZF_DEFAULT_OPTS+=" --bind=alt-j:down"
export FZF_DEFAULT_OPTS+=" --bind=alt-k:up"
export FZF_DEFAULT_OPTS+=" --bind=alt-h:backward-char"
export FZF_DEFAULT_OPTS+=" --bind=alt-l:forward-char"
export FZF_DEFAULT_OPTS+=" --bind=alt-x:delete-char"
export FZF_DEFAULT_OPTS+=" --bind=alt-X:backward-delete-char"
export FZF_DEFAULT_OPTS+=" --bind=alt-f:ignore"
export FZF_DEFAULT_OPTS+=" --bind=alt-w:forward-word"
export FZF_DEFAULT_OPTS+=" --bind=alt-b:backward-word"
export FZF_DEFAULT_OPTS+=" --bind=alt-d:kill-word"
export FZF_DEFAULT_OPTS+=" --bind=alt-$:end-of-line"
export FZF_DEFAULT_OPTS+=" --bind=alt-0:beginning-of-line"
export FZF_DEFAULT_OPTS+=" --bind=alt-D:kill-line"
export FZF_DEFAULT_OPTS+=" --bind=alt-u:unix-line-discard"

export FZF_DEFAULT_OPTS+=" --bind=alt-/:toggle-preview+refresh-preview"
export FZF_DEFAULT_OPTS+=" --bind=alt-\?:change-preview-window\(right\|bottom\)"
export FZF_DEFAULT_OPTS+=" --bind=ctrl-e:preview-down"
export FZF_DEFAULT_OPTS+=" --bind=ctrl-y:preview-up"
export FZF_DEFAULT_OPTS+=" --bind=alt-n:preview-down"
export FZF_DEFAULT_OPTS+=" --bind=alt-p:preview-up"
export FZF_DEFAULT_OPTS+=" --bind=alt-\.:preview-half-page-down"
export FZF_DEFAULT_OPTS+=" --bind=alt-\,:preview-half-page-up"
export FZF_DEFAULT_OPTS+=" --bind=ctrl-v:preview-page-down"
export FZF_DEFAULT_OPTS+=" --bind=alt-v:preview-page-up"
export FZF_DEFAULT_OPTS+=" --bind=alt-\>:preview-bottom"
export FZF_DEFAULT_OPTS+=" --bind=alt-\<:preview-top"
